[build-system]
requires = [
    "setuptools>=68",
]
build-backend = "setuptools.build_meta"

[project]
name = "gitCommit"
version = "0.1.12"
description = ""
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pylnlib",
    "pyyaml>=6.0.3",
    "tomli-w>=1.2.0",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
]

[project.scripts]
gitcommit = "gitcommit.main:main"

[project.license]
text = "MIT"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
ignore = [
    "E401",
    "E402",
    "E702",
    "E701",
]

[tool.pyright]
pythonVersion = "3.11"
typeCheckingMode = "standard"
reportUnusedVariable = "warning"
reportUnusedImport = "warning"
reportOptionalMemberAccess = "warning"
reportMissingTypeStubs = false

[tool.setuptools.packages.find]
where = [
    "src",
]

[tool.uv.sources.pylnlib]
path = "../pyLnLib"
editable = true
